### ISSUE TITLE
pods.pri content

### ISSUE THREAD

**Issue by sgaist** [qt-pods/qt-pods#14]
Hi,

Shouldn't pods.pri be "simply" a list of includes and INCLUDEPATH/LIBS be handled in their respective pods pri ?

e.g.

pods.pri:
include(qt-pods-core/qt-pods-core.pri)
include(qtwaitingspinner/qtwaitingspinner.pri)

qt-pods-core.pri:
INCLUDEPATH += \
    $$PWD

LIBS += \
    -L../qt-pods-core \
        -lqt-pods-core

and the same for qtwaitingspinner

**Comment by jacob3141** [comment]
You are correct. I simply wasn't aware of that cleaner solution, but it perfectly makes sense. I have translated all packages and also fixed all of them to stick to the naming conventions. I leave it up to you to review and close this issue.

**Comment by sgaist** [comment]
Good :+1: 
Implemented by:
https://github.com/cybercatalyst/qt-pods-core/commit/badd60cfcf5a967c0931ac30d24664c9355c54a5
and
https://github.com/cybercatalyst/qtwaitingspinner/commit/281a282a8043234d79e6cf8feeff989e975e1796
