### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by jcelerier** [qt-pods/qt-pods#23]
It would be nice to support CMake-based libraries, like KDE Frameworks : https://www.kde.org/info/kde-frameworks-5.6.0.php

**Comment by jacob3141** [comment]
We know that from a popularity perspective it is a bad thing not to support cmake, but unfortunately, cmake is not a part of Qt (but rather a specific of KDE projects). For instance, GNU projects use autotools to build Qt apps, which works fine.

The design principles of qt-pods aim for simplification, not for maximum compatibility. This decision has been made in the hope that it will save us a lot of trouble in the feature and keep the project maintainable, but also minimize headaches for the users. It should "just" work, and if we're honest, if projects really wants to be qt-pods compatible, it is not too hard to list all files in a pro and provide a pri for app integration even their everyday build system is different (for any other reasons).

Inqlude is a similar project trying to support each and everything. While it got a boost in the beginning by that policy, it is now choking on its own complexity. It is an objective decision to keep things simple.

Please also see: http://www.omg-it.works/coding-conventions-for-qtpods/

**Comment by jacob3141** [comment]
@jcelerier do you agree, so I can close this issue?

**Comment by jcelerier** [comment]
@cybercatalyst yes, it's sensible!

However I think that CMake is not far from being a first citizen in Qt world, given that Qt ships by default with CMake bindings and there are built-in commands & support for Qt projects in CMake (for uic, moc, rcc...).
