### ISSUE TITLE
Parallel building fails with ld: library not found for -lqtirc

### ISSUE THREAD

**Issue by uranusjr** [qt-pods/qt-pods#25]
I didn’t look deep into this, but it seems that qt-pods-gui depends on qtirc to build. So maybe

```
qt-pods-gui.depends = qtirc
```

is needed inside `qt-pods.pro`?

Tested on OS X 10.10 (Yosemite), Clang 6.0 (LLVM 3.5), Qt 5.4.1 with mkspec `macx-clang`

```
$ qmake
$ make -j4
```

**Comment by jacob3141** [comment]
Added in f7bfd81be. Can you verify?

**Comment by uranusjr** [comment]
Yup, seems to work now. :+1:
