### ISSUE TITLE
qt-pods support windows7?? compile problem and Webcore crashed..

### ISSUE THREAD

**Issue by ssjoon** [qt-pods/qt-pods#26]
I'm using windows7 and VS2010, qt-5.4.1 ..

in MainWindow::stdOutActivated function.. 
 read function is not recognized.. and i include io.h
and some library file path issue 

and i can launch qt-pods gui but crashed
WebCore::HTMLFormControlElement::isValidFormControlElement... 
Something wrong with webview.. so i delete webview in Development tab
then qt-pods-gui does not crash anymore.. 

in windows and latest qt.. qt-pods does not working well..

i'm new to qt but i want try to fix it ..

**Comment by jacob3141** [comment]
Hello ssjoon,

thank you for the valuable input. I will have a look at that. Unfortunately, atm I am very sick so please be patient here.

**Comment by jacob3141** [comment]
@ssjoon Do you have gathered any more insights?
