### ISSUE TITLE
Project ERROR: Unknown module(s) in QT: webkitwidgets

### ISSUE THREAD

**Issue by pendar747** [qt-pods/qt-pods#28]
I installed Qt 5.6 using the online installer and libqt5webkit5 and libqt5webkit5-dev using apt-get but I'm still unable to compile the code and get the following error:

```
make[1]: Entering directory '/home/pendar/Downloads/projects/qt-pods/qt-pods-gui'
/home/pendar/Qt/5.6/gcc_64/bin/qmake -o Makefile qt-pods-gui.pro
Project ERROR: Unknown module(s) in QT: webkitwidgets
Makefile:370: recipe for target 'Makefile' failed
make[1]: *** [Makefile] Error 3
make[1]: Leaving directory '/home/pendar/Downloads/projects/qt-pods/qt-pods-gui'
Makefile:123: recipe for target 'sub-qt-pods-gui-make_first' failed
make: *** [sub-qt-pods-gui-make_first] Error 2
```

I tried adding include and libs to the .pro file in the qui module:

```
INCLUDE += /usr/lib/x86_64-linux-gnu/libQt5WebKitWidgets.so.5.5 
LIBS += /usr/lib/x86_64-linux-gnu/libQt5WebKitWidgets.so.5.5 
```

which also didn't work!
Also tried symlinking or copying the installed libraries in `/usr/lib/x86_64-linux-gnu` to my Qt libs in `/home/pendar/Qt/5.6/gcc_64/lib` but that didn't work either

**Comment by uranusjr** [comment]
[Qt 5.6 does not work with Qt WebKit out-of-the-box anymore](https://wiki.qt.io/New_Features_in_Qt_5.6#Removed_Modules). You need to either use Qt 5.5.x or lower, or compile Qt WebKit directly from source.

As for this project’s concern, we should probably migrate to QtWebEngine. Some compatibility layer will be needed if early versions need to be supported. @cybercatalyst what do you think?

**Comment by buzzySmile** [comment]
It needs to be ported to Qt 5.6 according to [official porting guide from Qt WebKit to Qt WebEngine](http://doc.qt.io/qt-5/qtwebenginewidgets-qtwebkitportingguide.html).
I'd rather be told "has to be ported" for such forward-looking project as a qt-pods.

**Comment by jacob3141** [comment]
I have removed the dependency to WebKit for now. Please try again and close this if it works for you.

**Comment by buzzySmile** [comment]
Well done.
I've created [Pull request](https://github.com/qt-pods/qt-pods/pull/29) with TravisCI support which checks build with Qt5

I've check build with Qt 5.7 manually -- everything PASSED

**Comment by jacob3141** [comment]
Great, thanks!
